### ISSUE TITLE
Security Concern

### ISSUE THREAD

**Issue by daniellumleyuk** [dawutheuwad/PinguUnFryer3000#2]
Hello. The password for your application is exposed in your repository.
https://github.com/dawutheuwad/PinguUnFryer3000/blob/8d927af681a0f9b0777f24dc67a566756965f818/PinguUnfryer.py#L111
This could be a security risk.

**Comment by NotSteven1234** [comment]
The password being left there is intentional. It is part of the joke.

**Comment by NotSteven1234** [comment]
also its not even related to the roblox account itself. bruh.

**Comment by dawutheuwad** [comment]
as @NotSteven1234 said, i won't remove it, because its just part of a joke - you won't do anything without that password. this is why its also included in README.md

**Comment by dawutheuwad** [comment]
### Pinned to let others know that is not an issue and its meant to be in code.
